import type { Metadata } from "next";
import Link from "next/link";
import { Contact, LegalPage, List, Section } from "@/components/LegalPage";
import { JURISDICTION } from "@/lib/site";

export const metadata: Metadata = { title: "Terms of Service · Stock Council" };

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro={
        <p>
          These terms are an agreement between you and Stock Council (&quot;we&quot;, &quot;us&quot;) for your use of the Stock Council website and
          service. By creating an account, buying credits, or using the service, you agree to them. If you don&apos;t agree, please don&apos;t use
          Stock Council.
        </p>
      }
    >
      <Section n={1} title="Not investment advice">
        <div className="rounded-xl border border-amber-400/30 bg-amber-500/10 p-4 text-amber-100">
          Stock Council produces AI-generated research from public data. It is for information and education only. It is not investment,
          financial, tax, or legal advice, and it is not a recommendation to buy, sell, or hold any security.
        </div>
        <List>
          <li>
            We are not a registered investment adviser, dealer, or broker with any securities regulator in Canada, the United States, or
            elsewhere. Nothing on the site is personalized to your situation, goals, or risk tolerance.
          </li>
          <li>
            Reports are written by AI models and can be wrong, incomplete, out of date, or based on delayed or inaccurate source data. Ratings,
            scores, and outlooks are opinions generated by software, not predictions or guarantees.
          </li>
          <li>Investing involves risk, including loss of your money. Do your own research and consider talking to a licensed professional.</li>
          <li>You alone are responsible for your investment decisions and their results.</li>
        </List>
      </Section>

      <Section n={2} title="Who can use Stock Council">
        <p>
          You must be at least 18 years old (or the age of majority where you live) and able to enter a binding contract. You need an account
          with a verified email address to run analyses. Keep your password private; you&apos;re responsible for activity on your account. One
          account per person.
        </p>
      </Section>

      <Section n={3} title="Credits">
        <List>
          <li>Fresh analyses use credits. The number of credits each depth uses (Quick, Standard, Deep) is shown before you run it.</li>
          <li>Opening a stock that was analyzed recently, or a report in your history, is free.</li>
          <li>If an analysis fails, its credits are returned to your account automatically.</li>
          <li>
            Credits have no cash value, can&apos;t be transferred or sold, and can only be used on Stock Council. Free credits for new accounts are a
            promotion we may change or end at any time.
          </li>
          <li>
            Purchased credits don&apos;t expire while your account is open. Unused subscription credits roll over from month to month. If your
            account is closed or terminated, any remaining credits end with it.
          </li>
        </List>
      </Section>

      <Section n={4} title="Payments and subscriptions">
        <List>
          <li>
            Payments are processed by Stripe. Stripe may act as the seller of record for your purchase and handle applicable sales taxes; its
            terms also apply to the payment. We never see or store your full card details.
          </li>
          <li>Prices are shown on the pricing page in the currency charged, before any applicable taxes, which are added at checkout.</li>
          <li>
            Subscriptions (Plus, Pro) renew automatically each month and charge your payment method until you cancel. Each paid month adds that
            plan&apos;s credits to your account.
          </li>
          <li>
            You can cancel anytime from <span className="text-white">Manage billing</span> on the pricing page. Cancellation takes effect at the
            end of the current billing period; you keep your plan until then and keep the credits you already have.
          </li>
          <li>
            If you switch plans, the new price and the new plan&apos;s monthly credits start at your next billing date. There is no partial charge
            or refund for the switch.
          </li>
          <li>
            Except where the law requires otherwise, payments are non-refundable, including for unused credits or partial months. If you think
            you were charged in error, contact us and we&apos;ll look into it.
          </li>
          <li>
            We may change prices or the credits included in a plan. Changes to a subscription take effect from your next billing period, and we
            will tell you before they apply.
          </li>
        </List>
      </Section>

      <Section n={5} title="Reports and sharing">
        <List>
          <li>
            Reports are about publicly traded companies, not about you. A report generated for a stock may be shown to other users who open the
            same stock for a period of time afterward, and recently analyzed stocks may be listed on the site. Your own history list is private
            to your account.
          </li>
          <li>
            You may use reports for your own personal, non-commercial purposes. Don&apos;t resell them, republish them as your own, or present them
            as professional advice.
          </li>
          <li>
            Data comes from third-party and public sources (such as SEC filings, exchange data, economic data, and news feeds). We don&apos;t control
            those sources and don&apos;t guarantee their accuracy, completeness, or availability.
          </li>
        </List>
      </Section>

      <Section n={6} title="Acceptable use">
        <p>Don&apos;t:</p>
        <List>
          <li>use bots, scripts, or scraping to access the service or generate reports in bulk;</li>
          <li>create multiple accounts to collect free credits, or share or sell your account;</li>
          <li>try to get around credits, limits, payments, or security, or probe or disrupt the service;</li>
          <li>use Stock Council for anything unlawful, including market manipulation or misleading others about securities.</li>
        </List>
        <p>We may suspend or close accounts that break these rules, without refund of credits obtained through the violation.</p>
      </Section>

      <Section n={7} title="Availability and changes">
        <p>
          We work to keep Stock Council running, but it may be slow, interrupted, or changed at any time, and features (including data sources and
          analysts) may be added or removed. We may update these terms; if a change is material we&apos;ll post it here and update the date above,
          and continuing to use the service means you accept the updated terms.
        </p>
      </Section>

      <Section n={8} title="Disclaimers and limitation of liability">
        <p>
          Stock Council is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind, including accuracy, fitness for a particular
          purpose, or non-infringement, to the fullest extent the law allows.
        </p>
        <p>
          To the fullest extent the law allows, we are not liable for any investment losses, lost profits, or indirect, incidental, special, or
          consequential damages arising from your use of Stock Council or reliance on any report. Our total liability for any claim relating to
          the service is limited to the amount you paid us in the 12 months before the claim. Some places don&apos;t allow these limits, so they
          may not fully apply to you; nothing here limits rights you have under consumer protection law that can&apos;t be waived.
        </p>
      </Section>

      <Section n={9} title="Closing your account">
        <p>
          You can stop using Stock Council at any time and ask us to delete your account (see the{" "}
          <Link href="/privacy" className="text-brand-300 hover:underline">
            Privacy Policy
          </Link>
          ). Cancel any subscription first so you aren&apos;t charged again. We may suspend or close accounts that violate these terms or if we
          stop offering the service; if we discontinue the service entirely, we&apos;ll give reasonable notice.
        </p>
      </Section>

      <Section n={10} title="Governing law">
        <p>
          These terms are governed by the laws of {JURISDICTION}, and the courts there have jurisdiction over any dispute, unless the consumer
          laws where you live give you the right to bring a claim in your local courts.
        </p>
      </Section>

      <Section n={11} title="Contact">
        <p>
          <Contact />.
        </p>
      </Section>
    </LegalPage>
  );
}
